//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by painter.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   101
#define CG_ID_VIEW_LAYERDIALOG          103
#define ID_STATUSBAR_POS                106
#define ID_STATUSBAR_SIZE               107
#define ID_STATUSBAR_ITEM               108
#define ID_STATUSBAR_INFO               109
#define IDD_PAINTERFONTVIEW_FORM        110
#define CG_ID_VIEW_BRUSHDIALOG          111
#define ID_STATUSBAR_HOTKEYS            112
#define IDD_LAYERVIEW_FORM              113
#define IDR_LAYERVIEW_TMPL              114
#define CG_ID_VIEW_TOOLOPTIONS          118
#define ID_TOOLBAR_SHOW_TOOLFARBEN      120
#define ID_PAINT_ZOOMIN                 121
#define ID_PAINT_FILLED_CIRCLE          122
#define ID_PAINT_RECTANGLE              123
#define IDR_PAINTETYPE                  128
#define IDD_PALETTEEDIT                 131
#define IDR_PAINTERFONTVIEW_TMPL        133
#define IDD_NEWDOCUMENT                 145
#define IDD_BEARBEITEN_RESIZE           147
#define IDC_CURSOR_FREEHAND1            148
#define IDC_CURSOR_FREEHAND2            149
#define IDC_CURSOR_LINE                 151
#define IDC_CURSOR_RECT                 152
#define IDC_CURSOR_CIRCLE               153
#define IDC_CURSOR_FILL                 154
#define IDD_EINSTELLUNGEN               156
#define IDC_CURSOR_ZOOM                 165
#define IDC_CURSOR_SELECT               166
#define IDD_DIALOG_FILE_OPEN            174
#define IDD_DIALOG_BATCH                180
#define IDD_DIALOG_PROGRESS             181
#define IDC_CURSOR_HAND                 182
#define IDD_DIALOG_TEXT                 183
#define IDC_CURSOR_TEXT                 184
#define IDD_DIALOG_ANI                  185
#define IDD_DIALOG_CONVERT_OPTIONS      187
#define IDI_ICON_ACTIVE_LAYER           191
#define IDD_PTOOL_LAYER                 191
#define IDI_ICON_INACTIVE_LAYER         192
#define IDD_DIALOG_COLOR_PICKER         193
#define IDI_ICON_VISIBLE_LAYER          194
#define IDD_PROP_PROMPTS                195
#define IDI_ICON_INACTIVE_MASK          195
#define IDD_PROP_DOCUMENT               196
#define IDI_ICON_ACTIVE_MASK            196
#define IDD_DIALOG_GRADIENT             200
#define IDC_CURSOR_DRAGHAND             201
#define IDD_DIALOG_JPEG_OPTIONS         202
#define IDC_CURSOR_SELECT_ADD           202
#define IDD_PROP_DOCUMENT_2             203
#define IDC_CURSOR_SELECT_REMOVE        203
#define IDD_PROP_GRID                   204
#define IDD_DIALOG_CREATE_MASK          205
#define IDD_DIALOG_EFFEKTE              206
#define IDD_EFFEKT_BRIGHTNESS           207
#define IDD_EFFEKT_TEMPLATE             208
#define IDD_EFFEKT_AURA                 209
#define IDD_EFFEKT_GRAYSCALE            210
#define IDD_EFFEKT_COLORIZE             211
#define IDD_EFFEKT_DIFFUSOR             212
#define IDD_EFFEKT_SMOOTHEN             213
#define IDD_EFFEKT_JALOUSIE             214
#define IDD_EFFEKT_REDUCE               215
#define IDI_ICON_LAYER_NEW              221
#define IDI_ICON_LAYER_CREATEMASK       222
#define IDI_ICON_LAYER_MERGEVISIBLE     223
#define IDI_ICON_LAYER_MERGEALL         224
#define IDD_DIALOG_TO_FILL              224
#define IDD_DIALOG_SELECTPATTERN        225
#define IDD_EFFEKT_PIXELIZE             226
#define IDB_BITMAP_BACKGROUND           226
#define IDD_BASICTOOLDLG                227
#define IDD_DIALOG_IGF_OPTIONS          233
#define IDD_DIALOG_SELECTEFFEKT         234
#define IDD_DIALOG_TE_AURA              235
#define IDI_ICON_LAYER                  236
#define IDI_ICON_TOOLOPTIONS            238
#define IDD_DIALOG_RESIZE_CANVAS        238
#define IDD_EFFEKT_COLORDIFFUSOR        239
#define IDD_EFFEKT_PERLINNOISE          240
#define IDD_DIALOG_ROTATE               241
#define IDD_EFFEKT_BEVEL                242
#define IDC_CURSOR_PICKER               242
#define IDI_ICON_PICKER                 243
#define IDD_DIALOG_CREATE_FONT_FROM_WIN 243
#define IDC_CURSOR_FILLEDCIRCLE         243
#define IDD_EFFEKT_SHADOW               244
#define IDI_ICON_COLORKEY_LAYER         244
#define IDC_CURSOR_BOX                  244
#define IDI_ICON_TOOL_BROWSER           245
#define IDD_DIALOG_REPLACE_COLOR        246
#define IDD_DIALOG_LOAD_PALETTE         248
#define IDD_DIALOG_RENAME_LAYER         249
#define IDD_EFFEKT_PLASMA               250
#define IDD_EFFEKT_MERSENNE             251
#define IDD_DIALOG_PHOTOSHOP_FILTER     252
#define IDD_DIALOG_SELECT               253
#define IDD_EFFEKT_TILEABLE             254
#define IDR_BRUSHTIP_1PIXEL             254
#define IDD_DIALOG_TO_LINE              255
#define IDD_DIALOG_TO_FREEHAND2         256
#define IDI_ICON_ANIM_PLAY              259
#define IDI_ICON_ANIM_STOP              260
#define IDI_ICON_ANIM_HOME              261
#define IDI_ICON_ANIM_PREV              262
#define IDI_ICON_ANIM_NEXT              263
#define IDI_ICON_ANIM_END               264
#define IDI_ICON_ANIM_INSERT            265
#define IDI_ICON_ANIM_INSERT_BEHIND     266
#define IDI_ICON_ANIM_DELETE            267
#define IDI_ICON_MAIN_NEW               268
#define IDI_ICON_MAIN_OPEN              269
#define IDI_ICON_MAIN_SAVE              270
#define IDI_ICON_MAIN_PROPS             271
#define IDI_ICON_MAIN_DOC_PROPS         272
#define IDI_ICON_MAIN_ZOOMIN            273
#define IDI_ICON_MAIN_ZOOMOUT           274
#define IDI_ICON_TOOL_NONE              275
#define IDI_ICON_TOOL_FREEHAND_PIXEL    276
#define IDI_ICON_TOOL_FREEHAND_LINE     277
#define IDI_ICON_TOOL_ZOOM              278
#define IDI_ICON_TOOL_UNDO              279
#define IDI_ICON_TOOL_REDO              280
#define IDI_ICON_TOOL_RECT              281
#define IDI_ICON_TOOL_BOX               282
#define IDI_ICON_TOOL_ELLIPSE           283
#define IDI_ICON_TOOL_FILLED_ELLIPSE    284
#define IDI_ICON_TOOL_FILL              285
#define IDI_ICON_TOOL_TEXT              286
#define IDI_ICON_TOOL_SELECT            287
#define IDI_ICON_TOOL_CLEAR             288
#define IDI_ICON_TOOL_SNAP              289
#define IDI_ICON_TOOL_LINE              290
#define IDD_DLG_TOOLBARS                291
#define IDI_ICON_TOOL_SELECT1           291
#define IDI_ICON_TOOL_SELECT_COLOR      291
#define IDD_PTOOL_FARBEN                292
#define IDD_PTOOL_BRUSH                 293
#define IDD_PTOOL_FUNCTIONOPTIONS       294
#define IDB_BITMAP1                     294
#define IDD_PTOOL_BROWSER               295
#define IDD_PTOOL_TILETESTER            296
#define IDD_DIALOG_RENAME               297
#define IDD_PTOOL_ANIMATIONFRAME        298
#define IDD_DIALOG_TO_SELECTION         299
#define IDD_EFFEKT_CONTRAST             300
#define IDD_DIALOG_GIF_OPTIONS          301
#define IDC_SLIDER_R                    1000
#define IDC_SLIDER_G                    1001
#define IDC_SLIDER_B                    1002
#define IDC_TEXT_ROT                    1004
#define IDC_TEXT_GRUEN                  1005
#define IDC_TEXT_BLAU                   1006
#define IDC_BUTTON_VERLAUF              1007
#define IDC_BUTTON_WIN20                1008
#define IDC_BUTTON_GRAYSCALE            1009
#define IDC_EDIT_BREITE                 1012
#define IDC_EDIT_HOEHE                  1013
#define IDC_EDIT_FRAMES                 1014
#define IDC_EDIT_NEUE_BREITE            1014
#define IDC_EDIT_NEUE_HOEHE             1015
#define IDC_NEWDOCUMENT_TYPE            1026
#define IDC_NEWDOCUMENT_BITDEPTH        1027
#define IDC_RESIZE_BREITEALT            1028
#define IDC_RESIZE_HOEHEALT             1029
#define IDC_RESIZE_CHECK_KEEP_ASPECTRATIO 1034
#define IDC_BUTTON_TOOL_LAYER_NEWLAYER  1043
#define IDC_CHECK_FILE_OPEN_PREVIEW     1059
#define IDC_STATIC_FILE_OPEN_PREVIEW    1060
#define IDC_STATIC_FILE_OPEN_WIDTH      1061
#define IDC_STATIC_FILE_OPEN_HEIGHT     1062
#define IDC_BUTTON_TOOL_LAYER_MERGE     1063
#define IDC_STATIC_FILE_OPEN_DEPTH      1064
#define IDC_BUTTON_TOOL_LAYER_MERGE_ALL 1065
#define IDC_EDIT_FONT_ZEICHENNR         1066
#define IDC_STATIC_FILE_OPEN_FRAMES     1067
#define IDC_BUTTON_TOOL_LAYER_CREATE_MASK 1068
#define IDC_STATIC_FONT_ZEICHENNR       1069
#define IDC_STATIC_FILE_OPEN_TYPE       1070
#define IDC_SPIN_FONT_ZEICHENNR         1071
#define IDC_STATIC_FONT_INHALT          1072
#define IDC_EDIT_FONT_BREITE            1073
#define IDC_STATIC_PRE_VIEW             1074
#define IDC_SPIN_FONT_BREITE            1075
#define IDC_STATIC_POST_VIEW            1076
#define IDC_EDIT_FONT_HOEHE             1077
#define IDC_SPIN_FONT_HOEHE             1078
#define IDC_EDIT_FONT_XOFFSET           1080
#define IDC_SPIN_FONT_XOFFSET           1081
#define IDC_EDIT_FONT_YOFFSET           1082
#define IDC_SPIN_FONT_YOFFSET           1083
#define IDC_BUTTON_FILTER_ZOOMFAKTOR    1084
#define IDC_STATIC_FILTER_INFO          1102
#define IDC_LIST_BATCH_FILES            1103
#define IDC_EDIT_BATCH_TARGET           1105
#define IDC_BUTTON_BATCH_BROWSE_TARGET_PATH 1107
#define IDC_COMBO_BATCH_TYPE            1109
#define IDC_COMBO_BATCH_DEPTH           1111
#define IDC_LIST_BATCH_LOG              1113
#define IDC_BUTTON_BATCH_ADDFILE        1115
#define IDC_BUTTON_BATCH_REMOVEFILE     1117
#define IDC_BUTTON_BATCH_REMOVEALLFILES 1119
#define IDC_BUTTON_BATCH_START          1120
#define IDC_EDIT_BATCH_PALETTE          1121
#define IDC_STATIC_PROGRESS_INFO        1122
#define IDC_BUTTON_BATCH_BROWSEPALETTE  1123
#define IDC_STATIC_PROGRESS_PROZENT     1124
#define IDC_PROGRESS_BAR                1125
#define IDC_COMBO_RESIZE_ART            1126
#define IDC_CHECK_FILTER_NEWLAYER       1127
#define IDC_EDIT_TEXT_TEXT              1128
#define IDC_STATIC_TEXT_PREVIEW         1131
#define IDC_BUTTON_START_AC             1132
#define IDC_LIST_CA_FILES               1134
#define IDC_BUTTON_CA_ADDFILE           1135
#define IDC_BUTTON_CA_REMOVEFILE        1136
#define IDC_BUTTON_CA_REMOVEALLFILES    1137
#define IDC_EDIT_CA_PALETTE             1138
#define IDC_EDIT_CA_TARGET              1139
#define IDC_COMBO_CA_TYPE               1140
#define IDC_COMBO_CA_DEPTH              1141
#define IDC_LIST_CA_LOG                 1142
#define IDC_BUTTON_CA_BROWSEPALETTE     1143
#define IDC_BUTTON_CA_BROWSE            1144
#define IDC_RADIO_CONVERT_STRAIGHT      1145
#define IDC_RADIO_CONVERT_DITHER        1146
#define IDC_LIST_m_vectLayers           1147
#define IDC_BUTTON_BRUSH_FOREGROUND     1150
#define IDC_BUTTON_BRUSH_BACKGROUND     1151
#define IDC_STATIC_GRADIENT_PREVIEW     1151
#define IDC_BUTTON_CP_NEW_COLOR         1152
#define IDC_EDIT_GRADIENT_ANGLE         1152
#define IDC_PROP_DOC_WIDTH              1153
#define IDC_SPIN_GRADIENT_ANGLE         1153
#define IDC_BUTTON_CP_OLD_COLOR         1153
#define IDC_RADIO_JPEG_FAST             1154
#define IDC_PROP_DOC_USED_COLORS        1154
#define IDC_BUTTON_CP_VERLAUF_1         1154
#define IDC_RADIO_JPEG_ACCURATE         1155
#define IDC_PROP_DOC_SCROLLWIDTH        1155
#define IDC_BUTTON_CP_VERLAUF_2         1155
#define IDC_RADIO_JPEG_PERFEKT          1156
#define IDC_PROP_DOC_SCROLLHEIGHT       1156
#define IDC_PROP_DOC_DEPTH              1157
#define IDC_RADIO_JPEG_GUT              1157
#define IDC_EDIT_GRID_WIDTH             1157
#define IDC_RADIO_JPEG_NORMAL           1158
#define IDC_EDIT_GRID_HEIGHT            1158
#define IDC_RADIO_JPEG_DURCHSCHNITT     1159
#define IDC_EDIT_GRID_XOFFSET           1159
#define IDC_PROP_DOC_TYPE               1160
#define IDC_RADIO_JPEG_SCHLECHT         1160
#define IDC_EDIT_GRID_YOFFSET           1160
#define IDC_EDIT_TEXT_FONTSIZE          1161
#define IDC_CHECK_GRID                  1161
#define IDC_EDIT_TEXT_FONTWIDTH         1162
#define IDC_PROP_DOC_PATH               1163
#define IDC_EDIT_CP_HTML                1163
#define IDC_SPIN_TEXT_SIZE              1164
#define IDC_RADIO_CM_VOLL               1164
#define IDC_PROP_DOC_NAME               1165
#define IDC_RADIO_CM_WORKCOLOR          1165
#define IDC_SPIN_TEXT_WIDTH             1165
#define IDC_BUTTON_BRUSH_FOREGROUNDTYPE 1166
#define IDC_CHECK_CM_INVERT_MASK        1166
#define IDC_TREE_EFFEKTE                1167
#define IDC_RADIO_CM_SELECTION          1167
#define IDC_EDIT_TEXT_KERNING           1167
#define IDC_BUTTON_BRUSH_BACKGROUNDTYPE 1168
#define IDC_RADIO_CM_GRAYSCALE          1168
#define IDC_SPIN_TEXT_KERNING           1168
#define IDC_BUTTON_RENDER               1169
#define IDC_EDIT_TEXT_TILT              1169
#define IDC_EDIT_TIEFE                  1170
#define IDC_SPIN_TEXT_TILT              1170
#define IDC_EDIT_ITERATIONS             1172
#define IDC_COMBO_RICHTUNG              1175
#define IDC_COMBO_AUSRICHTUNG           1176
#define IDC_EDIT_COLORS                 1176
#define IDC_COMBO_FILLMODE              1177
#define IDC_BUTTON_ADD_PATTERN          1184
#define IDC_ODLIST_PATTERNS             1187
#define IDC_BUTTON_SWAPBRUSH            1188
#define IDC_EDIT_ABOUT_INFO             1189
#define IDC_EDIT_AURA_SIZE              1189
#define IDC_EDIT_WINKEL                 1189
#define IDC_REDIT_TOLERANZ              1190
#define IDC_EDIT_AURA_OFFSET            1190
#define IDC_COMBO_FONT                  1193
#define IDC_CHECK_IGF_WITHPAL           1195
#define IDC_CHECK_IGF_WITHCOMPRESSLIST  1196
#define IDC_LIST_EFFEKTE                1197
#define IDC_BUTTON_EFFEKTLISTE          1198
#define IDC_BUTTON_NEWEFFEKT            1199
#define IDC_BUTTON_TE_FARBE             1201
#define IDC_CHECK_EFFEKT_SINGLE         1202
#define IDC_CHECK_CENTER_H              1203
#define IDC_CHECK_CENTER_V              1204
#define IDC_EDIT_ABWEICHUNG             1204
#define IDC_CHECK_RED                   1205
#define IDC_CHECK_GREEN                 1206
#define IDC_CHECK_BLUE                  1207
#define IDC_RADIO_BOTH_DIRECTIONS       1208
#define IDC_CHECK_RED_INVERSE           1208
#define IDC_RADIO_UP                    1209
#define IDC_CHECK_GREEN_INVERSE         1209
#define IDC_RADIO_DOWN                  1210
#define IDC_CHECK_BLUE_INVERSE          1210
#define IDC_EDIT_STEPS                  1211
#define IDC_EDIT_SEED                   1212
#define IDC_EDIT_SCALE                  1213
#define IDC_RADIO_CW                    1213
#define IDC_RADIO_CCW                   1214
#define IDC_CHECK_ALLOW_RESIZE          1215
#define IDC_IBUTTON_PICKER              1217
#define IDC_BUTTON_SHIFT_PAL            1218
#define IDC_CHECK_REGISTER_FILETYPES    1219
#define IDC_CHECK_REGISTER_BTN          1220
#define IDC_NEWFONT_DEPTH               1220
#define IDC_CHECK_REGISTER_BTH          1221
#define IDC_REDIT_SHADOW_RANGE          1221
#define IDC_CHECK_REGISTER_FNX          1222
#define IDC_REDIT_SHADOW_OFFSET_X       1222
#define IDC_TREE_FILES                  1222
#define IDC_CHECK_REGISTER_FNH          1223
#define IDC_REDIT_SHADOW_OFFSET_Y       1223
#define IDC_CHECK_REGISTER_PNT          1224
#define IDC_BUTTON_COLOR_1              1225
#define IDC_BUTTON_COLOR_2              1226
#define IDC_RADIO_MAP_TO_PAL            1227
#define IDC_RADIO_FORCE_PAL             1228
#define IDC_EDIT_LAYER_NAME             1228
#define IDC_EDIT_NEW_NAME               1229
#define IDC_REDIT_FARBWERT              1230
#define IDC_COMBO_AURA_ART              1231
#define IDC_REDIT_SAETTIGUNG            1231
#define IDC_COMBO_GRAY_MODE             1232
#define IDC_REDIT_GRAYSCALE             1233
#define IDC_TREE_PS_FILTER              1234
#define IDC_LIST_SELECTION_RULES        1236
#define IDC_COMBO_ANDORXOR              1237
#define IDC_COMBO_RULE                  1238
#define IDC_REDIT_VALUE                 1239
#define IDC_BUTTON_ADD                  1240
#define IDC_REDIT_CP_ROT                1241
#define IDC_REDIT_CP_GRUEN              1242
#define IDC_REDIT_NEWWIDTH              1242
#define IDC_REDIT_CP_BLAU               1243
#define IDC_REDIT_NEWWIDTH_PERCENT      1243
#define IDC_REDIT_BRIGHTNESS            1243
#define IDC_REDIT_CP_HUE                1244
#define IDC_BUTTON_FONT                 1244
#define IDC_REDIT_UPPERBOUND            1244
#define IDC_REDIT_CP_SAT                1245
#define IDC_REDIT_NEWHEIGHT             1245
#define IDC_CHECK_FILLED                1245
#define IDC_REDIT_CP_LIGHT              1246
#define IDC_REDIT_NEWHEIGHT_PERCENT     1246
#define IDC_CHECK_AA                    1246
#define IDC_CHECK_CONNECTED             1247
#define IDC_REDIT_GRADIENT              1247
#define IDC_ANGLEWND                    1248
#define IDC_ODLIST_BRUSHTIPS            1249
#define IDC_ODLIST_THUMBS               1251
#define IDC_LIST_TOOLBARS               1252
#define IDC_IWND_TILESET                1254
#define IDC_COMBO_DOCUMENTS             1255
#define IDC_EDIT_WIDTH                  1256
#define IDC_EDIT_HEIGHT                 1257
#define IDC_BUTTON_REFRESH              1258
#define IDC_STATIC_TILETESTBED          1259
#define IDC_EDIT_MATRIX_11              1260
#define IDC_EDIT_MATRIX_12              1261
#define IDC_STATIC_OLD                  1261
#define IDC_EDIT_MATRIX_13              1262
#define IDC_EDIT_OLD_NAME               1262
#define IDC_EDIT_MATRIX_21              1263
#define IDC_STATIC_NEW                  1263
#define IDC_EDIT_MATRIX_22              1264
#define IDC_STATIC_FONT_PREVIEW         1264
#define IDC_EDIT_MATRIX_23              1265
#define IDC_GRADIENT_WND                1265
#define IDC_EDIT_MATRIX_31              1266
#define IDC_EDIT_MATRIX_32              1267
#define IDC_BUTTON_ADD_PEG              1267
#define IDC_EDIT_MATRIX_26              1268
#define IDC_EDIT_MATRIX_33              1268
#define IDC_BUTTON_COLOR                1268
#define IDC_REDIT_PEGPOS                1269
#define IDC_EDIT_GRADIENT_NAME          1270
#define IDC_BUTTON_SAVE_GRADIENT        1271
#define IDC_COMBO1                      1272
#define IDC_COMBO_PRESET_GRADIENTS      1272
#define IDC_EDIT_DELAY                  1273
#define IDC_BUTTON_PLAY_ANIM            1274
#define IDC_BUTTON_STOP_ANIM            1275
#define IDC_STATIC_DELAY                1276
#define IDC_CHECK1                      1277
#define IDC_CHECK_GRADIENT_CLIP         1277
#define IDC_CHECK_ROUNDED               1277
#define IDC_COMBO2                      1278
#define IDC_COMBO_GRADIENT_TYPE         1278
#define IDC_CHECK_SQUARE                1279
#define IDC_REDIT_LOWER                 1280
#define IDC_BTN_KILL_LETTER             1281
#define IDC_STATIC_FILTER_SETTINGS      1282
#define IDC_RADIO_GIF_87                1283
#define IDC_RADIO_GIF_89                1284
#define ID_PAINT_BOX                    32771
#define ID_PAINT_CIRCLE                 32772
#define ID_PAINT_LINE                   32774
#define ID_PAINT_FILL                   32775
#define ID_PAINT_ZOOMOUT                32776
#define ID_ANIM_PLAY                    32778
#define ID_ANIM_STOP                    32779
#define ID_ANIM_STEP_FORWARD            32780
#define ID_ANIM_STEP_BACK               32781
#define ID_ANIM_HOME                    32782
#define ID_ANIM_END                     32783
#define ID_ANIM_FRAME_DELETE            32784
#define ID_ANIM_FRAME_INSERT            32785
#define ID_PALETTE_LADEN                32786
#define ID_PALETTE_SPEICHERN            32787
#define ID_PALETTE_EDITIEREN            32788
#define ID_BEARBEITEN_EIGENSCHAFTEN     32791
#define ID_PAINT_SELECTION              32792
#define ID_BEARBEITEN_LOESCHEN          32793
#define ID_BEARBEITEN_RESIZE            32794
#define ID_PAINT_FREEHAND1              32795
#define ID_EDIT_PASTEASSELECTION        32796
#define ID_PAINT_FREEHAND2              32797
#define ID_EDIT_PASTEASNEWIMAGE         32798
#define ID_BEARBEITEN_PASTEASSELECTION  32799
#define ID_BEARBEITEN_PASTEASNEWIMAGE   32800
#define ID_PAINT_SELECTION_COLOR        32801
#define ID_SPECIAL_REMOVESELECTION      32804
#define ID_SPECIAL_REPLACE              32805
#define ID_ANIM_FRAME_INSERTBEHIND      32807
#define ID_PAINT_BRIGHTEN               32808
#define ID_PAINT_DARKEN                 32809
#define ID_BEARBEITEN_EINSTELLUNGEN     32810
#define ID_BEARBEITEN_DOKUMENTEINSTELLUNGEN 32811
#define ID_MENU_FONT_8TO16              32820
#define ID_PAINT_ZOOM                   32821
#define ID_PAINT_ARROW                  32822
#define ID_CONVERT_TO_8BPP              32823
#define ID_CONVERT_TO_16BPP             32824
#define ID_CONVERT_TO_24BPP             32825
#define ID_CONVERT_TO_32BPP             32826
#define ID_SPEZIAL_FILTER               32830
#define ID_BATCH_CONVERSION             32831
#define ID_MENU_SPEZIAL_SPLIT           32833
#define ID_BEARBEITEN_MIRRORH           32834
#define ID_BEARBEITEN_MIRRORV           32835
#define ID_BEARBEITEN_ROTIEREN          32836
#define ID_PAINT_TEXT                   32837
#define ID_EDIT_ZOOM_IN                 32838
#define ID_EDIT_ZOOM_OUT                32839
#define ID_MENU_ANI_CREATOR             32842
#define ID_MENU_UNDO                    32845
#define ID_MENU_COLORPICKER             32846
#define CG_ID_VIEW_TOGGLETOOLWINDOWS    32849
#define ID_BRUSH_TYPE_SOLID             32859
#define ID_BRUSH_TYPE_PATTERN           32860
#define ID_BRUSH_TYPE_GRADIENT          32861
#define ID_MENU_SPEZIAL_SPLIT_ALPHA     32863
#define ID_MENU_TOGGLE_SNAP             32864
#define IDS_TOOL_SNAP                   32864
#define ID_SPEZIAL_EFFEKTE              32869
#define ID_SPECIAL_SELECTION_ALSMASKE   32871
#define ID_SPECIAL_SELECTION_VONMASKE   32872
#define ID_SPECIAL_SELECTION_INVERT     32873
#define ID_MENU_REDO                    32879
#define ID_MENU_VIEW_DEBUG              32881
#define ID_BEARBEITEN_RESIZE_CANVAS     32882
#define ID_MENU_ROTATE_FREE             32883
#define ID_MENU_CREATE_FONT             32884
#define ID_MENU_COLOR_INVERT            32885
#define ID_MENU_SCRIPT_TEST             32886
#define ID_MENU_PS_FILTER               32887
#define ID_SPECIAL_SELECTION_FROM_DIALOG 32888
#define ID_SPEZIAL_AUF4BITKONVERTIEREN  32892
#define ID_SPEZIAL_AUF1BITKONVERTIEREN  32893
#define ID_SPEZIAL_KONVERTIERE          32894
#define ID_ANSICHT_TOOLBARS             32895
#define ID_ANSICHT_TOOLBARS32896        32896
#define ID_ANSICHT_TOOLBARS32897        32897
#define ID_ANSICHT_TOOLBARS32899        32899
#define ID_MENU_TOOLBARS                32901
#define ID_BEARBEITEN_ISOMETRISIEREN    32902
#define ID_BRUSH_TYPE_BRIGHTEN          32903
#define ID_BEARBEITEN_EXTRAS            32904
#define ID_EXTRAS_2XSAI                 32905
#define ID_SPEZIAL_INVERTIEREN          32906
#define ID_BEARBEITEN_EXPORTIEREN       32907
#define ID_BEARBEITEN_IMPORTIEREN       32908
#define ID_BEARBEITEN_EXPORTIEREN32909  32909
#define ID_BEARBEITEN_IMPORTIEREN32910  32910
#define ID_BEARBEITEN_RUNSCRIPT         32911
#define ID_BEARBEITEN_RUNSCRIPT32912    32912
#define ID_SPECIAL_EXCHANGECOLOR        32914
#define ID_SPEZIAL_EFFEKTE32915         32915
#define ID_FILE_CLOSEALL                32916
#define ID_DATEI_CLOSEALL               32917
#define ID_SPECIAL_SAFETYSAVE           32918
#define ID__TEST                        32919

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        297
#define _APS_NEXT_COMMAND_VALUE         32920
#define _APS_NEXT_CONTROL_VALUE         1284
#define _APS_NEXT_SYMED_VALUE           124
#endif
#endif
